blank_issues_enabled: false
contact_links:
  - name: Bidon Unity Plugin Documentation
    url: https://docs.bidon.org/docs/sdk/unity/get-started
    about: The place to get started with Bidon Unity Plugin.
