blank_issues_enabled: false
contact_links:
  - name: Bidon Unity Plugin Documentation
    url: https://github.com/bidon-io/bidon-unity-plugin/blob/main/README.md
    about: The place to get started with Bidon Unity Plugin.
